services:
  - type: web
    name: bot_sarsh-3
    env: node
    region: oregon
    plan: free
    buildCommand: echo "no build needed"
    startCommand: node --enable-source-maps ./dist/index.mjs
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
